version: "3.3"

services:
  app:
    image: 'pepega-vpn-manager:latest'
    build:
      context: .
    container_name: app
    restart: unless-stopped
    healthcheck:
      test: "curl --fail localhost:8800/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 3s
      retries: 3
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwertyui
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/pepegavpnmanager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwertyui
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    network_mode: host

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwertyui
      - POSTGRES_DB=pepegavpnmanager
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 6
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}