version: "3.3"

services:
  app:
    image: 'pepega-vpn-manager:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwertyui
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pepegavpnmanager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwertyui
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8800:8800"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwertyui
      - POSTGRES_DB=pepegavpnmanager
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}